=begin
  Even Fibonacci Numbers:
Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with 1 and 2, the first
10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.

=end
def even_fib_sum(limit)
  fib = [1,2]
  even = 2

  loop do
    break if limit <= fib[fib.length - 1]
    num = fib[fib.length - 1] + fib[fib.length - 2]

    fib << num
    if num.even?
      even += num
    end
  end
  even
end

even_fib_sum(4000000) #=> 4613732
